import { cx } from "class-variance-authority";
import type { Metadata } from "next";

import { Header } from "@/components/header";
import Provider from "@/components/provider";
import { getPostDir, readDir } from "@/lib/utils";

import "./globals.css";
import "./katex.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const teachingPosts = await readDir(getPostDir("teaching"));
  const projectPosts = await readDir(getPostDir("project"));

  return (
    <html lang="en">
      <body className={cx("flex w-full justify-center")}>
        <Provider>
          <div className="container">
            <Header teachingPosts={teachingPosts} projectPosts={projectPosts} />
            <div className="mt-60">{children}</div>
          </div>
        </Provider>
      </body>
    </html>
  );
}
