import { cx } from "class-variance-authority";
import type { Metadata } from "next";

import { Header } from "@/components/header";
import Provider from "@/components/provider";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cx("flex w-full justify-center")}>
        <Provider>
          <div className="w-full max-w-4xl px-2">
            <Header />
            {children}
          </div>
        </Provider>
      </body>
    </html>
  );
}
